In [2]:
import torch

In [5]:
x=torch.arange(12,dtype=torch.float)

In [ ]:
x.numel()

12

In [4]:
torch.__version__

'2.8.0+cu129'

In [5]:
x=torch.arange(12,dtype=torch.float32)

In [6]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [7]:
print(x.reshape(4,3))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [8]:
torch.zeros((2,3,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [10]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
torch.tensor([[1,2,3,4],[5,6,7,8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [1]:
#2.1.3 operations
import torch

In [3]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])

In [6]:
x+y,x-y,x*y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([ 1.,  4., 16., 64.]))

In [12]:
x=torch.arange(12,dtype=torch.float32).reshape(3,4)
y=torch.tensor([[2,1,3,4],[1,2,3,4],[4,3,2,1]],dtype=torch.float32)
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  3.,  4.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
#broafcasting
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)

In [40]:
x,y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[  2.,  -2.,  -3.,  -5.],
         [-11., -13., -15., -17.],
         [-20., -24., -28., -32.]]))

In [ ]:
before=id(x)
x=x+y
id(x)==before# this is an out-place operation, first, we create a new tensor x+y， then Y is assigned to the new space

False

In [ ]:
before=id(x)
x+=y
id(x)==before #this is an in-place operation, and the a will not point to a new space

True

In [ ]:
Z=torch.zeros_like(y)
before=id(Z)
Z[:]=x+y
id(Z)==before# this is an in-place operation and the space to which pointed by Z is not changed

True

In [ ]:
Z=torch.zeros_like(y)
before=id(Z)
Z=x+y
id(Z)==before# this is an out-place operation and the space to which pointed by Z is changed

False

In [46]:
#2.1.6 the conversion between ndarray and the tensor
A=x.numpy()
B=torch.from_numpy(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)