In [1]:
import torch

In [3]:
x=torch.tensor(3)
y=torch.tensor(2)

In [4]:
x+y,x-y,x*y,x//y

(tensor(5), tensor(1), tensor(6), tensor(1))

In [6]:
x=torch.arange(3,dtype=torch.float64)
print(x)

tensor([0., 1., 2.], dtype=torch.float64)


In [7]:
# matrices
A=torch.arange(6).reshape(2,3)

In [8]:
A

tensor([[0, 1, 2],
        [3, 4, 5]])

a=2


In [10]:
a=2
X=torch.arange(24).reshape(2,3,-1)

In [14]:
Y=X.clone()

In [16]:
id(Y)==id(X)

False

In [20]:
X.sum()

tensor(276)

In [21]:
A=torch.arange(6).reshape(2,3)

In [22]:
A.sum()

tensor(15)

In [23]:
A

tensor([[0, 1, 2],
        [3, 4, 5]])

In [24]:
A.sum(axis=0)

tensor([3, 5, 7])

In [25]:
import numpy as np

In [27]:
kaka=np.arange(12).reshape(3,4)

In [28]:
kaka

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
kaka.sum(axis=0)

array([12, 15, 18, 21])

In [30]:
A.sum()==A.sum(axis=[0,1])

tensor(True)

In [33]:
A

tensor([[0, 1, 2],
        [3, 4, 5]])

In [37]:
A.to(torch.float64)

tensor([[0., 1., 2.],
        [3., 4., 5.]], dtype=torch.float64)

In [40]:
A.mean(), A.sum()/A.numel()

(tensor(2.5000, dtype=torch.float64), tensor(2.5000, dtype=torch.float64))

In [42]:
A.mean(axis=1)#==A.sum(axis=1)/A.shape[1]

tensor([1., 4.], dtype=torch.float64)

In [ ]:
A.sum(axis=0).shape,A.sum(axis=0,keepdim=True).shape,A.shape
#keepdim will not change the calculation result, however, it will help keep the original dim unchanged!

(torch.Size([3]), torch.Size([1, 3]), torch.Size([2, 3]))

In [53]:
A/A.sum(axis=0)

tensor([[0.0000, 0.2000, 0.2857],
        [1.0000, 0.8000, 0.7143]], dtype=torch.float64)

In [57]:
A/A.sum(axis=0),A/A.sum(axis=0,keepdim=True)

(tensor([[0.0000, 0.2000, 0.2857],
         [1.0000, 0.8000, 0.7143]], dtype=torch.float64),
 tensor([[0.0000, 0.2000, 0.2857],
         [1.0000, 0.8000, 0.7143]], dtype=torch.float64))

In [60]:
A==A.cumsum(axis=0)

tensor([[ True,  True,  True],
        [ True, False, False]])

In [ ]:
A.cumsum(axis=0)#it is the accumulation along the direction of axis sum, that is the head sevrral row

tensor([[0., 1., 2.],
        [3., 5., 7.]], dtype=torch.float64)

In [64]:
A=torch.arange(6).reshape(2,3)

In [65]:
A

tensor([[0, 1, 2],
        [3, 4, 5]])

In [71]:
A=torch.arange(6).reshape(2,3)
B=torch.arange(6,12).reshape(3,2)
torch.mm(A,B),A@B

(tensor([[ 28,  31],
         [100, 112]]),
 tensor([[ 28,  31],
         [100, 112]]))

In [74]:
#it will be a L2 norm
torch.norm(torch.tensor([3.0,4.0]))
#L1 norm
torch.abs(torch.tensor([3.0,-4.0])).sum()

tensor(7.)

In [ ]:
#exercise 2.3.13
x=torch.arange(24).reshape(2,3,4)
len(x)
#so the len of a tensor will return its axis0 number

2

In [91]:
A=torch.tensor([[1,3],[7.,5.]])

In [97]:
A/A.sum(axis=1,keepdim=True),A/A.sum(axis=1)

(tensor([[0.2500, 0.7500],
         [0.5833, 0.4167]]),
 tensor([[0.2500, 0.2500],
         [1.7500, 0.4167]]))

In [96]:
A.sum(axis=1)


tensor([ 4., 12.])